//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado via T4.
//
//     Alterações feitas neste arquivo podem ser perdidas
//     caso o código seja regerado. 
// </auto-generated>
//------------------------------------------------------------------------------
#region [ Diretivas de Using ]
using FGV.PISA.Application.Model;
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
#endregion

namespace  FGV.PISA.Application.Model
{
	///<summary>Tabela Arquivos</summary>
	public partial class Arquivos :  BaseModel
	{
		

		public int id_Resultado { get; set; }

		public string NomeArquivo { get; set; }

		public string URLArquivo { get; set; }

		public string Pais { get; set; }

		public string Regiao { get; set; }

		public string Estrato { get; set; }

		public string Escola { get; set; }

		public string Estudante { get; set; }

		public virtual Resultado Resultado { get; set; }

	}

}
