//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado via T4.
//
//     Alterações feitas neste arquivo podem ser perdidas
//     caso o código seja regerado. 
// </auto-generated>
//------------------------------------------------------------------------------
#region [ Diretivas de Using ]
using FGV.PISA.Application.Model;
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
#endregion

namespace  FGV.PISA.Application.Model
{
	///<summary>Tabela Escola</summary>
	public partial class Escola :  BaseModel
	{
		public string Codigo { get; set; }

		public string Nome { get; set; }

		public virtual ICollection<Aluno> Aluno { get; set; } = Enumerable.Empty<Aluno>().ToList();

		public virtual ICollection<Usuario> Usuario { get; set; } = Enumerable.Empty<Usuario>().ToList();

	}

}
