//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado via T4.
//
//     Alterações feitas neste arquivo podem ser perdidas
//     caso o código seja regerado. 
// </auto-generated>
//------------------------------------------------------------------------------
#region [ Diretivas de Using ]
using FGV.PISA.Application.Model;
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
#endregion

namespace  FGV.PISA.Application.Model
{
	///<summary>Tabela Exames_pisa</summary>
	public partial class Exames_pisa :  BaseModel
	{
		

		public string Descricao { get; set; }

		public int Ano { get; set; }

		public virtual ICollection<Funcoes_menu> Funcoes_menu { get; set; } = Enumerable.Empty<Funcoes_menu>().ToList();

		public virtual ICollection<Resultado> Resultado { get; set; } = Enumerable.Empty<Resultado>().ToList();

	}

}
