//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado via T4.
//
//     Alterações feitas neste arquivo podem ser perdidas
//     caso o código seja regerado. 
// </auto-generated>
//------------------------------------------------------------------------------
#region [ Diretivas de Using ]
using FGV.PISA.Application.Model;
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
#endregion

namespace  FGV.PISA.Application.Model
{
	///<summary>Tabela Funcoes</summary>
	public partial class Funcoes :  BaseModel
	{
		
		public string nome { get; set; }

		public string descricao { get; set; }

		public virtual ICollection<Funcoes_menu> Funcoes_menu { get; set; } = Enumerable.Empty<Funcoes_menu>().ToList();

	}

}
