//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado via T4.
//
//     Alterações feitas neste arquivo podem ser perdidas
//     caso o código seja regerado. 
// </auto-generated>
//------------------------------------------------------------------------------
#region [ Diretivas de Using ]
using FGV.PISA.Application.Model;
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
#endregion

namespace  FGV.PISA.Application.Model
{
	///<summary>Tabela Funcoes_menu</summary>
	public partial class Funcoes_menu :  BaseModel
	{
		public int id { get; set; }

		public int exames_pisa_id { get; set; }

		public int funcao_id { get; set; }

		public int menu_id { get; set; }

		public DateTime? data_inicio_vigencia { get; set; }

		public DateTime? data_fin_vigencia { get; set; }

		public DateTime? data_vira_so_leitura { get; set; }

		public virtual Exames_pisa Exames_pisa { get; set; }

		public virtual Funcoes Funcoes { get; set; }

		public virtual Menu Menu { get; set; }

	}

}
