//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado via T4.
//
//     Alterações feitas neste arquivo podem ser perdidas
//     caso o código seja regerado. 
// </auto-generated>
//------------------------------------------------------------------------------
#region [ Diretivas de Using ]
using FGV.PISA.Application.Model;
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
#endregion

namespace  FGV.PISA.Application.Model
{
	///<summary>Tabela Menu</summary>
	public partial class Menu :  BaseModel
	{
		
		public string code { get; set; }

		public string nome { get; set; }

		public string nome_exibicao { get; set; }

		public int pai_id { get; set; }

		public int posicao { get; set; }

		public string icone { get; set; }

		public bool ativo { get; set; }

		public string action { get; set; }

		public string controller { get; set; }

		public string url { get; set; }

		public DateTime dataCriacao { get; set; }

		public DateTime? dataAtualizacao { get; set; }

		public DateTime? DataInicioVigencia { get; set; }


		public DateTime? DataFinVigencia { get; set; }


		public DateTime? DataViraSoLeitura { get; set; }

		public bool EstaVigente { get; set; }

	}

}
