//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado via T4.
//
//     Alterações feitas neste arquivo podem ser perdidas
//     caso o código seja regerado. 
// </auto-generated>
//------------------------------------------------------------------------------
#region [ Diretivas de Using ]
using FGV.PISA.Application.Model;
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
#endregion

namespace  FGV.PISA.Application.Model
{
	///<summary>Tabela Resultado</summary>
	public partial class Resultado :  BaseModel
	{
		
		public DateTime Data_Envio { get; set; }

		public DateTime Data_Avaliacao { get; set; }

		public int Turno { get; set; }

		public int id_usuario { get; set; }

		public int? id_aluno { get; set; }

		public int exames_pisa_id { get; set; }

		public virtual Aluno Aluno { get; set; }

		public virtual Exames_pisa Exames_pisa { get; set; }

		public virtual Usuario Usuario { get; set; }

		public virtual ICollection<Arquivos> Arquivos { get; set; } = Enumerable.Empty<Arquivos>().ToList();

	}

}
