//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado via T4.
//
//     Alterações feitas neste arquivo podem ser perdidas
//     caso o código seja regerado. 
// </auto-generated>
//------------------------------------------------------------------------------
#region [ Diretivas de Using ]
using FGV.PISA.Application.Model;
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
#endregion

namespace  FGV.PISA.Application.Model
{
	///<summary>Tabela Usuarios_funcoes</summary>
	public partial class Usuarios_funcoes :  BaseModel
	{		

		public int usuario_id { get; set; }

		public int funcao_id { get; set; }

		public int exames_pisa_id { get; set; }

		public virtual Usuario Usuario { get; set; }

		public virtual Funcoes Funcao { get; set; }

		public virtual Exames_pisa Exames_Pisa { get; set; }

	}

}
