//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado via T4.
//
//     Alterações feitas neste arquivo podem ser perdidas
//     caso o código seja regerado. 
// </auto-generated>
//------------------------------------------------------------------------------
#region [ Diretivas de Using ]
using FGV.PISA.Application.Model;
using FGV.PISA.CrossCutting.Common;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
#endregion

namespace FGV.PISA.Web.Models
{
	///<summary>Tabela Usuario</summary>
	public partial class UsuarioModel : BaseViewModel
	{
		#region Privates
		private string _cpf;
		#endregion

		[Required(ErrorMessage = "Digite o CPF.")]
		public string Cpf { get => _cpf != null ? _cpf.Replace(".", "").Replace("-", "") : _cpf; set => _cpf = value; }
		public string Nome { get; set; }

		public string Email { get; set; }

		public string Telefone { get; set; }

		public int id_escola { get; set; }

		public string Senha { get; set; }

		public List<MenuViewModel> Menu { get; set; }

		public UsuarioModel()
		{
			this.Menu = new List<MenuViewModel>();
		}

		public UsuarioModel(Usuario data)
		{
			if (data == null) return;
			this.Id = data.Id;
			this.DataCriacao = data.DataCriacao;
			this.DataAtualizacao = data.DataAtualizacao;
			this.Ativo = data.Ativo;
			this.Cpf = data.Cpf;
			this.Nome = data.Nome;
			this.Email = data.Email;
			this.Telefone = data.Telefone;
			this.id_escola = data.id_escola;
			this.Senha = data.Senha;
		}

		public Usuario ToDataBaseEntity()
		{
			Usuario usuario = new Usuario();
			usuario.Id = this.Id;
			usuario.DataCriacao = this.DataCriacao;
			usuario.DataAtualizacao = DateTimeBrasilia.Now();
			usuario.Ativo = this.Ativo;
			usuario.Cpf = this.Cpf;
			usuario.Nome = this.Nome;
			usuario.Email = this.Email;
			usuario.Telefone = this.Telefone;
			usuario.id_escola = this.id_escola;
			usuario.Senha = this.Senha;

			return usuario;
		}
	}
}
